
package wsclient.fuji.url;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "wsGetLinkSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsGetLinkSoap {


    /**
     * 
     * @param numeroDeAcceso
     * @param locexpirationSeconds
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/obtenerLink")
    @WebResult(name = "obtenerLinkResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "obtenerLink", targetNamespace = "http://tempuri.org/", className = "wsclient.fuji.url.ObtenerLink")
    @ResponseWrapper(localName = "obtenerLinkResponse", targetNamespace = "http://tempuri.org/", className = "wsclient.fuji.url.ObtenerLinkResponse")
    public String obtenerLink(
        @WebParam(name = "numeroDeAcceso", targetNamespace = "http://tempuri.org/")
        String numeroDeAcceso,
        @WebParam(name = "locexpirationSeconds", targetNamespace = "http://tempuri.org/")
        Integer locexpirationSeconds);

    /**
     * 
     * @param numeroDeAcceso
     * @param locexpirationSeconds
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/obtenerLinkB64")
    @WebResult(name = "obtenerLinkB64Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "obtenerLinkB64", targetNamespace = "http://tempuri.org/", className = "wsclient.fuji.url.ObtenerLinkB64")
    @ResponseWrapper(localName = "obtenerLinkB64Response", targetNamespace = "http://tempuri.org/", className = "wsclient.fuji.url.ObtenerLinkB64Response")
    public String obtenerLinkB64(
        @WebParam(name = "numeroDeAcceso", targetNamespace = "http://tempuri.org/")
        String numeroDeAcceso,
        @WebParam(name = "locexpirationSeconds", targetNamespace = "http://tempuri.org/")
        Integer locexpirationSeconds);

    /**
     * 
     * @param numeroAcceso
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/obtenerNumeroAccesoEncriptado")
    @WebResult(name = "obtenerNumeroAccesoEncriptadoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "obtenerNumeroAccesoEncriptado", targetNamespace = "http://tempuri.org/", className = "wsclient.fuji.url.ObtenerNumeroAccesoEncriptado")
    @ResponseWrapper(localName = "obtenerNumeroAccesoEncriptadoResponse", targetNamespace = "http://tempuri.org/", className = "wsclient.fuji.url.ObtenerNumeroAccesoEncriptadoResponse")
    public String obtenerNumeroAccesoEncriptado(
        @WebParam(name = "numeroAcceso", targetNamespace = "http://tempuri.org/")
        String numeroAcceso);

    /**
     * 
     * @param numeroAcceso
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/obtenerNumeroAccesoEncriptadoB64")
    @WebResult(name = "obtenerNumeroAccesoEncriptadoB64Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "obtenerNumeroAccesoEncriptadoB64", targetNamespace = "http://tempuri.org/", className = "wsclient.fuji.url.ObtenerNumeroAccesoEncriptadoB64")
    @ResponseWrapper(localName = "obtenerNumeroAccesoEncriptadoB64Response", targetNamespace = "http://tempuri.org/", className = "wsclient.fuji.url.ObtenerNumeroAccesoEncriptadoB64Response")
    public String obtenerNumeroAccesoEncriptadoB64(
        @WebParam(name = "numeroAcceso", targetNamespace = "http://tempuri.org/")
        String numeroAcceso);

}
