
package wsclient.fuji;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ReportWebServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReportWebServiceSoap {


    /**
     * 
     * @param vchAccessionNumber
     * @return
     *     returns wsclient.fuji.Response
     */
    @WebMethod(action = "http://tempuri.org/reporteBase64")
    @WebResult(name = "reporteBase64Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "reporteBase64", targetNamespace = "http://tempuri.org/", className = "wsclient.fuji.ReporteBase64")
    @ResponseWrapper(localName = "reporteBase64Response", targetNamespace = "http://tempuri.org/", className = "wsclient.fuji.ReporteBase64Response")
    public Response reporteBase64(
        @WebParam(name = "vchAccessionNumber", targetNamespace = "http://tempuri.org/")
        String vchAccessionNumber);

    /**
     * 
     * @param vchAccessionNumber
     * @return
     *     returns wsclient.fuji.Response
     */
    @WebMethod(action = "http://tempuri.org/reporteLogoBase64")
    @WebResult(name = "reporteLogoBase64Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "reporteLogoBase64", targetNamespace = "http://tempuri.org/", className = "wsclient.fuji.ReporteLogoBase64")
    @ResponseWrapper(localName = "reporteLogoBase64Response", targetNamespace = "http://tempuri.org/", className = "wsclient.fuji.ReporteLogoBase64Response")
    public Response reporteLogoBase64(
        @WebParam(name = "vchAccessionNumber", targetNamespace = "http://tempuri.org/")
        String vchAccessionNumber);

    /**
     * 
     * @param vchAccessionNumber
     * @return
     *     returns wsclient.fuji.Response
     */
    @WebMethod(action = "http://tempuri.org/reporteHtmlBase64")
    @WebResult(name = "reporteHtmlBase64Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "reporteHtmlBase64", targetNamespace = "http://tempuri.org/", className = "wsclient.fuji.ReporteHtmlBase64")
    @ResponseWrapper(localName = "reporteHtmlBase64Response", targetNamespace = "http://tempuri.org/", className = "wsclient.fuji.ReporteHtmlBase64Response")
    public Response reporteHtmlBase64(
        @WebParam(name = "vchAccessionNumber", targetNamespace = "http://tempuri.org/")
        String vchAccessionNumber);

}
